### ISSUE TITLE
fix left bar styles for root files in tree view

### ISSUE THREAD

**Issue by datsfilipe** [datsfilipe/datsfilipe.dev#31]
# Description

Look at the files on the bottom, the line at the left of them do not connect with each other as it does with the other files inside a folder (node).

![image](https://github.com/datsfilipe/datsfilipe.dev/assets/76636791/996680eb-d331-46a0-9590-cb56be8fa92b)

**Comment by Vidhanvyrs** [comment]
hey @datsfilipe  I am interested in this issue So Can you please explain a little bit more about the issue By [continuous](url) what do you mean ?
![image](https://github.com/datsfilipe/datsfilipe.dev/assets/94836010/107205e0-26c7-4749-9b25-17d0d691c725)

**Comment by datsfilipe** [comment]
hi @Vidhanvyrs, can u see that the files, instead of the folders, have this line on the left, right? inside the folders, they're connected and looks good, but the files that aren't in any folder have this line separated, so to fix you would need to find the problem in the styles and solve it. The styles are done with tailwind mostly.

**Comment by Vidhanvyrs** [comment]
Got it @datsfilipe gonna start working on it !

**Comment by datsfilipe** [comment]
hi, @Vidhanvyrs, can you tell me if you're still working on it?

**Comment by Vidhanvyrs** [comment]
yes I am it's just it is taking longer than i thought But don't worry I'll probably PR you till tomorrow
