### ISSUE TITLE
Wrong styles for headings

### ISSUE THREAD

**Issue by datsfilipe** [datsfilipe/datsfilipe.dev#32]
# Issue

- Too much spacing between headings
- Text size is the same for different headings (e.g. h2, h3, etc)

***As you can see here:***

![image](https://github.com/datsfilipe/datsfilipe.dev/assets/76636791/5f1cf21f-87ef-4119-aac0-9d1ec98c74e9)

**Comment by Honey2339** [comment]
can u assign me this issue?

**Comment by ghost** [comment]
Hey I was wondering which File / Folder is this currently happening at?

**Comment by datsfilipe** [comment]
> Hey I was wondering which File / Folder is this currently happening at?

Some of the custom styles for the markdown content are in `src/styles/global.css`. If I'm right, `.prose` is the class in which those styles are applied.

**Comment by ghost** [comment]
> > Hey I was wondering which File / Folder is this currently happening at?
> 
> Some of the custom styles for the markdown content are in `src/styeles/global.css`. If I'm right, `.prose` is the class in which those styles are applied.

Where is `.prose` class used in? Where is the code in that image located btw. 
![image](https://github.com/datsfilipe/datsfilipe.dev/assets/102673419/0d0f0fa0-8a30-4d1a-9b61-ae628269f0b5)

**Comment by datsfilipe** [comment]
@Tiensuperman I mean, you could search within your editor for it, but it's used in the layouts if I'm not mistaken. As I said, it's a tailwind class, so you need to modify the cascading styles in the global css file.
